app:
  image:
    repositoryPrefix: 436648017334.dkr.ecr.us-east-1.amazonaws.com/tech-challenge
    tag: latest
  imagePullPolicy: Always
  replicas: 1
  resources:
    requests:
      cpu: "300m"
      memory: "512Mi"
    limits:
      cpu: "600m"
      memory: "1Gi"
  hpa:
    minReplicas: 2
    maxReplicas: 3
    averageUtilization: 60

#db:
#  image: postgres:13
#  storage:
#    size: 1Gi

secrets:
  webhook:
    ACCESS_TOKEN_MERCADO_PAGO: substituir
    NOTIFICATION_URL_NGROK: substituir
  rds: #TODO substituir valores abaixo
    SPRING_DATASOURCE_URL: ""
    SPRING_DATASOURCE_USERNAME: "tech_challenge"
    SPRING_DATASOURCE_PASSWORD: "TyH2qEhgnIj41B"
    SPRING_DATASOURCE_DATABASE: "product"

controller:
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
    externalTrafficPolicy: Cluster

  ingressClassResource:
    name: nginx
    default: false

  metrics:
    enabled: true

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
