apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-product-service
spec:
  selector:
    app: {{ .Release.Name }}-product-app
  ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
  type: ClusterIP
  externalTrafficPolicy: Local
