apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret

type: Opaque
stringData:
  ACCESS_TOKEN_MERCADO_PAGO: {{ .Values.secrets.webhook.ACCESS_TOKEN_MERCADO_PAGO | default "" }}
  NOTIFICATION_URL_NGROK: {{ .Values.secrets.webhook.NOTIFICATION_URL_NGROK | default "" }}

  SPRING_DATASOURCE_URL: "jdbc:postgresql://tech-challenge-postgres.cqzusoauy3mw.us-east-1.rds.amazonaws.com:5432/{{ .Values.secrets.rds.SPRING_DATASOURCE_DATABASE}}"
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.rds.SPRING_DATASOURCE_USERNAME | default "" }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.rds.SPRING_DATASOURCE_PASSWORD | default "" }}